package xzeroair.trinkets.util.config;

public class ConfigDefaultReusedConstants {

    public static String[] EMPTY_STRING_ARRAY = {};

    public static String[] TREASURE_BLOCKS_DECIMAL = new String[]{
            //@formatter:off
            "oreCoal;4605510",
            "oreIron;16764057",
            "oreGold;16766720",
            "oreLapis;2515356",
            "oreRedstone;11546150",
            "oreDiamond;59135",
            "oreEmerald;65357",
            "oreQuartz;15461355",
            "minecraft:chest;*;16766720",
            "minecraft:chest_minecart;16766720"
            //@formatter:on
    };

    public static String[] DEFAULT_HEAVY_ARMOR = {
            //@formatter:off
            "minecraft:chainmail_helmet;*;0.01",
            "minecraft:chainmail_chestplate;*;0.09",
            "minecraft:chainmail_leggings;*;0.075",
            "minecraft:chainmail_boots;*;0.025",
            "Iron;head;0.025",
            "Iron;chest;0.15",
            "Iron;legs;0.075",
            "Iron;feet;0.05",
            "minecraft:golden_helmet;*;0.04",
            "minecraft:golden_chestplate;*;0.2",
            "minecraft:golden_leggings;*;0.1",
            "minecraft:golden_boots;*;0.06",
            "Diamond;0.075",
            //@formatter:on
    };

    public static String[] DEFAULT_ATTRIBUTE_LIST = {
            //@formatter:off
            "Name:generic.maxHealth, Amount:0, Operation:0",
            "Name:generic.knockbackResistance; Amount:0; Operation:0",
            "Name:generic.movementSpeed, Amount:0, Operation:0",
            "Name:generic.attackDamage, Amount:0, Operation:0",
            "Name:generic.attackSpeed, Amount:0, Operation:0",
            "Name:generic.armor, Amount:0, Operation:0",
            "Name:generic.armorToughness, Amount:0, Operation:0",
            "Name:generic.luck, Amount:0, Operation:0",
            "Name:generic.reachDistance, Amount:0, Operation:0",
            "Name:forge.swimSpeed, Amount:0, Operation:0",
            "Name:xat.entityMagic.regen, Amount:0, Operation:0",
            "Name:xat.entityMagic.regen.cooldown, Amount:0, Operation:0",
            "Name:xat.entityMagic.affinity, Amount:0, Operation:0",
            "Name:xat.jump, Amount:0, Operation:0",
            "Name:xat.stepheight, Amount:0, Operation:0"
            //@formatter:on
    };

    public static final String[] DEFAULT_CLIMB_LIST = new String[]{
            //@formatter:off
            "minecraft:dirt",
            "minecraft:grass",
            "minecraft:sand",
            "minecraft:*cobblestone*",
            "minecraft:*planks*",
            "minecraft:*stairs",
            "minecraft:*slab",
            "minecraft:*slab2",
            "minecraft:stone",
            "minecraft:gravel",
            "minecraft:gold_ore",
            "minecraft:iron_ore",
            "minecraft:coal_ore",
            "minecraft:log",
            "minecraft:sponge",
            "minecraft:glass",
            "minecraft:lapis_ore",
            "minecraft:lapis_block",
            "minecraft:sandstone",
            "minecraft:wool",
            "minecraft:gold_block",
            "minecraft:iron_block",
            "minecraft:brick_block",
            "minecraft:bookshelf",
            "minecraft:obsidian",
            "minecraft:diamond_ore",
            "minecraft:diamond_block",
            "minecraft:redstone_ore",
            "minecraft:ice",
            "minecraft:snow",
            "minecraft:clay",
            "minecraft:pumpkin",
            "minecraft:netherrack",
            "minecraft:soul_sand",
            "minecraft:glowstone",
            "minecraft:lit_pumpkin",
            "minecraft:stained_glass",
            "minecraft:stonebrick",
            "minecraft:melon_block",
            "minecraft:mycelium",
            "minecraft:nether_brick",
            "minecraft:end_stone",
            "minecraft:emerald_ore",
            "minecraft:emerald_block",
            "minecraft:quartz_ore",
            "minecraft:quartz_block",
            "minecraft:stained_hardened_clay",
            "minecraft:log2",
            "minecraft:prismarine",
            "minecraft:sea_lantern",
            "minecraft:hay_block",
            "minecraft:hardened_clay",
            "minecraft:coal_block",
            "minecraft:packed_ice",
            "minecraft:red_sandstone",
            "minecraft:purpur_block",
            "minecraft:purpur_pillar",
            "minecraft:end_bricks",
            "minecraft:magma",
            "minecraft:nether_wart_block",
            "minecraft:red_nether_brick",
            "minecraft:bone_block",
            "minecraft:concrete",
            "minecraft:concrete_powder",
            "minecraft:leaves",
            "minecraft:dispenser",
            "minecraft:noteblock",
            "minecraft:sticky_piston",
            "minecraft:piston",
            "minecraft:tnt",
            "minecraft:chest",
            "minecraft:crafting_table",
            "minecraft:furnace",
            "minecraft:cactus",
            "minecraft:jukebox",
            "minecraft:trapdoor",
            "minecraft:iron_bars",
            "minecraft:glass_pane",
            "minecraft:enchanting_table",
            "minecraft:end_portal_frame",
            "minecraft:redstone_lamp",
            "minecraft:ender_chest",
            "minecraft:beacon",
            "minecraft:anvil",
            "minecraft:trapped_chest",
            "minecraft:daylight_detector",
            "minecraft:redstone_block",
            "minecraft:hopper",
            "minecraft:dropper",
            "minecraft:stained_glass_pane",
            "minecraft:leaves2",
            "minecraft:iron_trapdoor",
            "minecraft:slime",
            "minecraft:end_rod",
            "minecraft:chorus_plant",
            "minecraft:chorus_flower",
            "minecraft:observer",
            "minecraft:*_shulker_box",
            "minecraft:*_glazed_terracotta",
            "minecraft:sign",
            "minecraft:wooden_door",
            "minecraft:iron_door",
            "minecraft:bed",
            "minecraft:flower_pot",
            "minecraft:skull",
            "minecraft:armor_stand",
            "minecraft:spruce_door",
            "minecraft:birch_door",
            "minecraft:jungle_door",
            "minecraft:dark_oak_door",
            "minecraft:acacia_door"
            //@formatter:on
    };

}
