plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'wtf.gofancy.fancygradle' version '1.1.+'
}
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.

fancyGradle {
    patches {
        resources
        coremods
        asm
        mergetool
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'Sponge / Mixin'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
    maven {
        url = uri('https://www.cursemaven.com')
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
    flatDir {
        dirs 'libs\\'
    }
}

//version = "${minecraft_version}-${version}"
version = "${version}"
group = "dev.xzeroair.${mod_id}"
base {
    archivesName = "${mod_name}-Forge-${minecraft_version}"
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
}

// Using the default Java version Minecraft is being shipped with
//java.toolchain.languageVersion = JavaLanguageVersion.of(8)
java.toolchain.getLanguageVersion().set(JavaLanguageVersion.of(8))

minecraft {
    mappings channel: 'stable', version: '39-1.12'

    copyIdeResources = true
    // Automatically enable AccessTransformers if the file exists
    if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
        accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    }

    runs {
        client {
            args "--username=XzeroAir", "--uuid=f5f28614-4e8b-4788-ae78-b020493dc5cb"
            jvmArg "-Dfml.coreMods.load=${mixin_loader_class}"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"
            workingDirectory 'run'
            ideaModule "${project.name}.main"
            taskName 'Client'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                Trinkets { source sourceSets.main }
            }
        }
        server {
            workingDirectory 'runServer'
            ideaModule "${project.name}.main"
            taskName 'Server'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                Trinkets { source sourceSets.main }
            }
        }
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
//    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    //Mixin
    implementation "org.spongepowered:mixin:${mixin_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    implementation "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    implementation fileTree(dir: 'libs', include: '*.jar')
    //FermiumBooter
    //implementation fg.deobf("curse.maven:fermiumbooter-${fermiumbooter_version}")

    implementation fg.deobf("curse.maven:jei-${jei_version}")

    //FlatDir Mods
//    implementation fg.deobf("libs:SRParasites:${srparasites_version}") //Third party distro disabled

    //CurseMaven Mods
    implementation fg.deobf("curse.maven:baubles-227083:2518667")
    implementation fg.deobf("curse.maven:first-aid-276837:4414252")
//    implementation fg.deobf("curse.maven:elenai-dodge-373104:3575333")
//    implementation fg.deobf("curse.maven:betterquesting-${betterquesting_version}")
    implementation fg.deobf("curse.maven:lycanitesmobs-${lycanitesmobs_version}")
    implementation fg.deobf("curse.maven:mobends-${mobends_version}")
    implementation fg.deobf("curse.maven:potioncore-${potioncore_version}")
    implementation fg.deobf("curse.maven:scalinghealth-${scalinghealth_version}")

    implementation fg.deobf("curse.maven:reskillable-286382:2815686")
    implementation fg.deobf("curse.maven:quark-243121:2924091")
//    implementation fg.deobf("curse.maven:electroblobs-wizardry-265642:4284076")
    implementation fg.deobf("curse.maven:electroblobs-wizardry-265642:6950392")
    implementation fg.deobf("curse.maven:antique-atlas-227795:2823030")
//    implementation fg.deobf("curse.maven:carry-on-274259:3271178")
    implementation fg.deobf("curse.maven:carry-on-274259:4507139")
//    implementation fg.deobf("curse.maven:iceandfire-rlcraft-${infrlcraft_version}")
//    implementation fg.deobf("curse.maven:wolf-armor-and-storage-253689:3648545")

    implementation fg.deobf("curse.maven:artemislib-313590:2741812")
    implementation fg.deobf("curse.maven:tough-as-nails-246391:2710969")
    implementation fg.deobf("curse.maven:elenai-dodge-373104:3575333")
    implementation fg.deobf("curse.maven:enhancedvisuals-255389:3507523")
    implementation fg.deobf("curse.maven:simpledifficulty-360779:3613814")

    //CurseMaven Libs
    implementation fg.deobf("curse.maven:silentlib-${silentlib_version}")
    implementation fg.deobf("curse.maven:autoreglib-${autoreglib_version}")
    implementation fg.deobf("curse.maven:llibrary-${llibrary_version}")

}

jar {
    manifest {
        attributes([
                'Specification-Title'        : mod_name,
                'Specification-Vendor'       : mod_authors,
                'Specification-Version'      : project.version,
//                'Specification-Version'   : project.jar.archiveVersion,
                'Implementation-Title'       : project.name,
                'Implementation-Version'     : project.version,
                'Implementation-Vendor'      : mod_authors,
                'Implementation-Timestamp'   : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Timestamp'                  : System.currentTimeMillis(),
                'Built-On-Java'              : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Built-On-Minecraft'         : minecraft_version,
//                'FMLCorePlugin': mixin_loader_class,
                'FMLCorePluginContainsFMLMod': 'true',
                'ForceLoadAsMod'             : 'true', //Comment out in dev environment, uncomment for building
//                'TweakClass'                 : 'org.spongepowered.asm.launch.MixinTweaker'
        ])
    }
}

processResources {
    filesMatching(['mcmod.info', 'pack.mcmeta', 'mods.toml', 'META-INF/mods.toml', 'mixins.json', '*.mixins.json']) {
        expand project.properties
    }

    //move access transformers into META-INF
    rename '(.+_at.cfg)', 'META-INF/$1'
}

jar.finalizedBy('reobfJar')

//publishing {
//    publications {
//        mavenJava(MavenPublication) {
//            artifactId base.archivesName.get()
//            from components.java
//            fg.component(it)
//        }
//    }
//    repositories {
//        maven {
//            url "file://" + System.getenv("local_maven")
//        }
//    }
//}
