# Project
version=0.33.3
group=dev.xzeroair.xat
minecraft_version=1.12.2
logo_file=
pack_version=3
# Forge
# The Forge version must agree with the Minecraft version
# https://files.minecraftforge.net/
forge_version=14.23.5.2860
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[14,15)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[14,15)
# The mod's supported Minecraft Version range
mc_version_range=[1.12.2,1.13)
forge_gradle_version=6.+
# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.4.1
# Mod options
mod_id=xat
mod_name=Trinkets and Baubles
# Review your options at https://choosealicense.com/
mod_license=General Public License Version 3
mod_authors=XzeroAir
mod_description=A mod full of trinkets and baubles.
mod_page=https://www.curseforge.com/minecraft/mc-mods/trinkets-and-baubles
source=https://github.com/XzeroAir/Trinkets
issue_tracker=https://github.com/XzeroAir/Trinkets/issues
update_url=https://github.com/XzeroAir/Trinkets/blob/1.12.2/update.json
mixin_loader_class=xzeroair.trinkets.XatMixinsPlugin
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# dependencies
# fermiumbooter
fermiumbooter_version=968474:6741950
# flatdir mods
srparasites_version=1.12.2v1.9.21
# cursemaven mods
baubles_version=227083:2518667
betterfoliage_version=228529:3393955
betterquesting_version=238856:2950248
bettersurvival_version=260360:5729552
callablehorses_version=331746:3568565
charm_version=318872:3146596
chunkanimator_version=236484:3850023
defiledlands_version=273502:2835318
epicsiegemod_version=229449:2920048
infrlcraft_version=888556:6596246
#infrlcraft_version=888556:7291902
inspirations_version=284007:2843007
jei_version=238222:5060339
#jei_version=238222:5846804
lycanitesmobs_version=224770:5750564
mobends_version=231347:3573346
potioncore_version=242872:2905184
quark_version=243121:2924091
rlartifacts_version=819886:4475428
rlcombat_version=711714:5940474
rustic_version=256141:6031613
scalinghealth_version=248027:2816920
spartanweaponry_version=278141:4393116
silentlib_version=242998:2851111
# cursemaven libs
autoreglib_version=250363:2746011
llibrary_version=243298:2504999
#llibrary_version=243298:3116493